const state = { plants: [], animal: 'all', mode: 'simple', query: '' };
const els = { search: document.querySelector('#search'), results: document.querySelector('#results'), empty: document.querySelector('#empty'), summary: document.querySelector('#summary'), sources: document.querySelector('#source-list') };
const sourceInfo = {
  'rabbit-diet': { label: 'Rabbit Welfare Association & Fund · rabbit diet', url: 'https://rabbitwelfare.co.uk/rabbit-care-advice/rabbit-diet/' },
  'poultry-feed': { label: 'Merck Veterinary Manual · feeding poultry', url: 'https://www.merckvetmanual.com/poultry/nutrition-and-management-of-poultry/feeding-poultry' },
  'aspca-toxic': { label: 'ASPCA · toxic and non-toxic plants', url: 'https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants' },
  'merck-plants': { label: 'Merck Veterinary Manual · overview of plant poisoning', url: 'https://www.merckvetmanual.com/toxicology/plant-poisoning/overview-of-plant-poisoning' }
};
const labels = { safe: 'Good starting point', caution: 'Use care', avoid: 'Avoid', unknown: 'Needs checking' };
const statusClass = { safe: 'status-safe', caution: 'status-caution', avoid: 'status-avoid', unknown: 'status-unknown' };
function statusFor(plant) { if (state.animal === 'all') { const values = Object.values(plant.status); return values.includes('avoid') ? 'avoid' : values.includes('caution') ? 'caution' : 'safe'; } return plant.status[state.animal] || 'unknown'; }
function filtered() { const q = state.query.trim().toLowerCase(); return state.plants.filter(p => { const matches = !q || [p.name, p.scientific, ...(p.aliases || [])].join(' ').toLowerCase().includes(q); const relevant = state.animal === 'all' || p.status[state.animal]; return matches && relevant; }).sort((a,b) => { const rank = { avoid: 0, caution: 1, safe: 2, unknown: 3 }; return rank[statusFor(a)] - rank[statusFor(b)] || a.name.localeCompare(b.name); }); }
function card(plant) { const status = statusFor(plant); const advanced = state.mode === 'advanced'; return `<article class="group rounded-2xl border border-[#ebe4d6] bg-paper p-4 transition hover:-translate-y-0.5 hover:border-moss hover:shadow-md"><div class="flex items-start justify-between gap-3"><div><h3 class="font-display text-xl font-bold">${plant.name}</h3><p class="mt-0.5 text-xs italic text-[#789086]">${plant.scientific}</p></div><span class="${statusClass[status]} shrink-0 rounded-full px-2.5 py-1 text-[11px] font-bold">${labels[status]}</span></div><p class="mt-4 text-sm leading-6 text-[#557064]">${advanced ? plant.why : plant.part + '. ' + (status === 'safe' ? 'A cited forage option when clean and correctly identified.' : status === 'caution' ? 'Read the note before offering.' : 'Keep away and read the note.')}</p><button class="mt-4 text-sm font-bold text-moss underline decoration-moss/30 underline-offset-4 hover:decoration-moss" data-detail="${plant.id}">View details →</button></article>`; }
function render() { const list = filtered(); els.results.innerHTML = list.map(card).join(''); els.empty.classList.toggle('hidden', list.length > 0); els.results.classList.toggle('hidden', list.length === 0); const noun = list.length === 1 ? 'plant' : 'plants'; els.summary.innerHTML = `<span><strong class="text-ink">${list.length}</strong> ${noun} shown${state.query ? ` for “${escapeHtml(state.query)}”` : ''}</span><span class="hidden sm:inline">${state.mode === 'simple' ? 'Simple view · tap for details' : 'Advanced view · notes shown'}</span>`; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function showDetail(id) { const p = state.plants.find(x => x.id === id); if (!p) return; const status = statusFor(p); const dialog = document.createElement('dialog'); dialog.className = 'm-auto w-[calc(100%-2rem)] max-w-lg rounded-3xl border border-[#d9e1cf] bg-paper p-0 text-ink shadow-2xl backdrop:bg-[#243836]/25'; dialog.innerHTML = `<div class="p-6 sm:p-8"><div class="flex items-start justify-between gap-4"><div><span class="${statusClass[status]} inline-flex rounded-full px-3 py-1 text-xs font-bold">${labels[status]}</span><h2 class="mt-4 font-display text-4xl font-bold">${p.name}</h2><p class="mt-1 text-sm italic text-[#789086]">${p.scientific}</p></div><button data-close class="grid h-9 w-9 place-items-center rounded-full bg-sage text-xl" aria-label="Close details">×</button></div><dl class="mt-7 grid gap-4 border-y border-[#ebe4d6] py-5 text-sm"><div><dt class="font-bold text-moss">Part checked</dt><dd class="mt-1 text-[#557064]">${p.part}</dd></div><div><dt class="font-bold text-moss">Why this flag?</dt><dd class="mt-1 leading-6 text-[#557064]">${p.why}</dd></div><div><dt class="font-bold text-moss">For ${state.animal === 'all' ? 'both animals' : state.animal + 's'}</dt><dd class="mt-1 text-[#557064]">${p.status.rabbit === p.status.hen ? labels[p.status.rabbit] : `Rabbit: ${labels[p.status.rabbit]} · Hen: ${labels[p.status.hen]}`}</dd></div></dl><p class="mt-5 text-xs leading-5 text-[#789086]">Plant ID and exposure details matter. This is a quick reference, not veterinary advice. For a suspected poisoning, contact a veterinarian promptly.</p><div class="mt-5 flex flex-wrap gap-2">${p.sources.map(id => `<a class="rounded-full bg-sage px-3 py-2 text-xs font-bold text-moss hover:bg-[#cfe0bf]" href="${sourceInfo[id].url}" target="_blank" rel="noreferrer">Source ↗</a>`).join('')}</div></div>`; document.body.append(dialog); dialog.showModal(); dialog.querySelector('[data-close]').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', e => { if (e.target === dialog) dialog.close(); }); dialog.addEventListener('close', () => dialog.remove()); }
function renderSources() { els.sources.innerHTML = `<p class="text-xs font-bold uppercase tracking-[.14em] text-moss">References used in the cards</p><ul class="mt-3 grid gap-2 text-sm sm:grid-cols-2">${Object.values(sourceInfo).map(s => `<li><a class="font-semibold text-moss underline decoration-moss/30 underline-offset-4 hover:decoration-moss" href="${s.url}" target="_blank" rel="noreferrer">${s.label} ↗</a></li>`).join('')}</ul>`; }
document.addEventListener('click', e => { const detail = e.target.closest('[data-detail]'); if (detail) showDetail(detail.dataset.detail); const animal = e.target.closest('[data-animal]'); if (animal) { state.animal = animal.dataset.animal; document.querySelectorAll('.animal-button').forEach(b => b.classList.toggle('pill-active', b === animal)); render(); } const mode = e.target.closest('[data-mode]'); if (mode) { state.mode = mode.dataset.mode; document.querySelectorAll('.mode-button').forEach(b => { b.classList.toggle('pill-active', b === mode); b.classList.toggle('text-moss', b !== mode); }); render(); } });
els.search.addEventListener('input', e => { state.query = e.target.value; render(); });
fetch('data/plants.json').then(r => r.json()).then(plants => { state.plants = plants; renderSources(); render(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {}); }).catch(() => { els.summary.textContent = 'Plant data could not be loaded.'; });
